export const WalletActionTypes = {
  FETCH_WALLET_INFO_START: "FETCH_WALLET_INFO_START",
  FETCH_WALLET_INFO_SUCCESS: "FETCH_WALLET_INFO_SUCCESS",
  FETCH_WALLET_INFO_FAILURE: "FETCH_WALLET_INFO_FAILURE",
};
