export const transactionTypes = {
  POST_TRANSACTION_START: "POST_TRANSACTION_START",
  POST_TRANSACTION_SUCCESS: "POST_TRANSACTION_SUCCESS",
  POST_TRANSACTION_FAILURE: "POST_TRANSACTION_FAILURE",
  CLEAR_TRANSACTIONS: "CLEAR_TRANSACTIONS",
};
